project:
  type: website
  output-dir: docs

website:
  title: "Xiao Yu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1 Notes"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2 Notes"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3 Notes"
      - text: "Labs"
        menu:
          - href: labs/lab_0/script
            text: "Lab 0: dplyr Basics"
          - href: labs/lab1/week-03/script/week3_lab_exercise.qmd
            text: "Lab 1"
            
      - text: "Assignments"
        menu:
          - href: Assignments/Assignment1/Assignment_1.qmd
            text: "Assignment 1: Census Data Exploration"
   
            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
