project:
  type: website
  output-dir: docs

website:
  title: "Xiao Yu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1 Notes"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2 Notes"
            

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
